---
title: "Datos ordenados y fechas"
author: "Ronny Hernández Mora"
date: "6/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hflights)
library(tibble)
library(tidyr)
library(dplyr)
library(janitor)
library(lubridate)
```

# Datos ordenados

Esto viene del concepto de `tidy data`

## Crear data frame de ejemplo

```{r}
datos_tidy <- data.frame(
  curso = c("mate", "arte", "compu"),
  fecha = c("2020-05-28", "2020-06-04", "2020-06-12"),
  calificacion = c("excelente", "regular", "bueno"),
  estudiantes = c(34, 20, 28)
)
```

## Usar funciones `pivot_wider` y `pivot_longer`

```{r}
datos_desordenados <- datos_tidy %>% 
  pivot_wider(curso, 
              names_from = calificacion, 
              values_from = estudiantes)
```


```{r}
datos_ordenados <- datos_desordenados %>% 
  pivot_longer(-curso,
               names_to = "calificacion",
               values_to = "total_estudiantes",
               values_drop_na = TRUE)
```

## Uso de funciones `unite` y `separate`

Unir columnas:

```{r}
unidos <- datos_ordenados %>% 
  unite(col = "nueva_columna",
        calificacion:total_estudiantes,
        sep = "/")
```

Separar columnas:

```{r}
separado <- unidos %>% 
  separate(col = nueva_columna,
           into = c("calificacion", "estudiantes"),
           sep = "/")
```

# Fechas

## Pasos para ordenar conjunto de datos y obtener variable de fecha

```{r}
vuelos <- hflights %>% 
  clean_names() %>% 
  unite(col = "fecha",
        year:dayof_month,
        sep = "-") %>% 
  mutate(fecha = ymd(fecha))
```

## Clases de fechas y ejemplos con `lubridate`

```{r}
class("2021-06-24")

class(ymd("2021-06-24"))

year("2021-06-24")

month("2021-06-24")
```

## Intervalos

```{r}
intervalo <- interval(ymd("2011-01-01"), ymd("2011-02-28"))

filtro_intervalo <- vuelos %>% 
  filter(fecha %within% intervalo)
```


